name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@main
        with:
          COMMIT_MESSAGE: ðŸ¤“Github action updated readme with a â„±á»®Å‡ â„±Î”Ä†Å¦ðŸ¤“ # default - Update with quote-readme
          OPTION: funfact           # default - both, can be one of (quote, funfact, both), if 'both' then will display either a quote or a fact
