name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ github.token }}
          stale-issue-message: 'Stale🥀. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
          exempt-issue-labels: '🍄𝓔👢👢 Ⓜ𝓔,👑 Winner!'
          exempt-issue-assignees: 't1noo7'
          exempt-pr-assignees: 't1noo7'
